import { Menu } from "@/types/Menu";

export const menuData: Menu[] = [
  {
    id: 1,
    title: "Marketing Materials",
    newTab: false,
    path: "/",
    submenu: [
      {
        id: 11,
        title: "Flyers",
        newTab: false,
        path: "/flyers",
      },
      {
        id: 12,
        title: "Business Cards",
        newTab: false,
        path: "/business-cards",
      },
      {
        id: 13,
        title: "Posters",
        newTab: false,
        path: "/posters",
      },
      {
        id: 14,
        title: "Catalogs",
        newTab: false,
        path: "/catalogs",
      },
      {
        id: 15,
        title: "Stickers & Labels",
        newTab: false,
        path: "/stickers-labels",
      },
      {
        id: 16,
        title: "Roll-Up",
        newTab: false,
        path: "/roll-up",
      },
      {
        id: 17,
        title: "Vouchers",
        newTab: false,
        path: "/vouchers",
      },
      {
        id: 18,
        title: "Plano Sheets",
        newTab: false,
        path: "/plano-sheets",
      },
    ],
  },
  {
    id: 2,
    title: "Business Printing",
    newTab: false,
    path: "/",
    submenu: [
      {
        id: 21,
        title: "Letterhead Paper",
        newTab: false,
        path: "/letterhead-paper",
      },
      {
        id: 22,
        title: "Stamps",
        newTab: false,
        path: "/stamps",
      },
      {
        id: 23,
        title: "Presentation Folders A4/A5",
        newTab: false,
        path: "/presentation-folders",
      },
      {
        id: 24,
        title: "Envelopes",
        newTab: false,
        path: "/envelopes",
      },
      {
        id: 25,
        title: "Notebooks",
        newTab: false,
        path: "/notebooks",
      },
      {
        id: 26,
        title: "Calendars",
        newTab: false,
        path: "/calendars",
      },
      {
        id: 27,
        title: "HoReCa",
        newTab: false,
        path: "/horeca",
      },
    ],
  },
  {
    id: 3,
    title: "Outdoor Advertising",
    newTab: false,
    path: "/",
    submenu: [
      {
        id: 31,
        title: "Banners",
        newTab: false,
        path: "/banners",
      },
      {
        id: 32,
        title: "Mesh Banners",
        newTab: false,
        path: "/mesh-banners",
      },
      {
        id: 33,
        title: "A-Boards",
        newTab: false,
        path: "/a-boards",
      },
      {
        id: 34,
        title: "Signs and Plaques",
        newTab: false,
        path: "/signs-and-plaques",
      },
      {
        id: 35,
        title: "Custom Printed Flags",
        newTab: false,
        path: "/custom-printed-flags",
      },
      {
        id: 36,
        title: "Window and Vehicle Wrapping Films",
        newTab: false,
        path: "/window-and-vehicle-wrapping-films",
      },
      {
        id: 37,
        title: "Frosted Window Films",
        newTab: false,
        path: "/frosted-window-films",
      },
      {
        id: 38,
        title: "Magnetic Films",
        newTab: false,
        path: "/magnetic-films",
      },
    ],
  },
  {
    id: 4,
    title: "Large Format Printing",
    newTab: false,
    submenu: [
      {
        id: 41,
        title: "CAD Printing",
        newTab: false,
        path: "/cad-printing",
      },
      {
        id: 42,
        title: "Graphic Printing",
        newTab: false,
        path: "/graphic-printing",
      },
      {
        id: 43,
        title: "Banners",
        newTab: false,
        path: "/banners-large-format",
      },
    ],
  },
  {
    id: 5,
    title: "Branded Textiles",
    newTab: false,
    submenu: [
      {
        id: 51,
        title: "Custom Printed Clothing",
        newTab: false,
        path: "/custom-printed-clothing",
      },
      {
        id: 52,
        title: "Printed Tote Bags",
        newTab: false,
        path: "/printed-tote-bags",
      },
    ],
  },
  {
    id: 6,
    title: "Branded Merchandise",
    newTab: false,
    submenu: [
      {
        id: 61,
        title: "Custom Mugs",
        newTab: false,
        path: "/custom-mugs",
      },
      {
        id: 62,
        title: "Custom Pens",
        newTab: false,
        path: "/custom-pens",
      },
      {
        id: 63,
        title: "Custom Printed Lanyards",
        newTab: false,
        path: "/custom-printed-lanyards",
      },
      {
        id: 64,
        title: "Custom Stress Balls",
        newTab: false,
        path: "/custom-stress-balls",
      },
      {
        id: 65,
        title: "Branded Deck Chairs",
        newTab: false,
        path: "/branded-deck-chairs",
      },
    ],
  },
  {
    id: 7,
    title: "Packaging, Stickers & Labels",
    newTab: false,
    submenu: [
      {
        id: 71,
        title: "Stickers and Labels",
        newTab: false,
        path: "/stickers-and-labels",
      },
      {
        id: 72,
        title: "Printed Boxes",
        newTab: false,
        path: "/printed-boxes",
      },
      {
        id: 73,
        title: "Customer Paper Bags",
        newTab: false,
        path: "/custom-paper-bags",
      },
      {
        id: 74,
        title: "Printed Packing Tapes",
        newTab: false,
        path: "/printed-packing-tapes",
      },
      {
        id: 75,
        title: "Frosted Window Films",
        newTab: false,
        path: "/frosted-window-films",
      },
      {
        id: 76,
        title: "Magnetic Films",
        newTab: false,
        path: "/magnetic-films",
      },
    ],
  },
  {
    id: 8,
    title: "Event Materials",
    newTab: false,
    submenu: [
      {
        id: 81,
        title: "Invitation Cards",
        newTab: false,
        path: "/invitation-cards",
      },
      {
        id: 82,
        title: "Place Cards",
        newTab: false,
        path: "/place-cards",
      },
      {
        id: 83,
        title: "Custom Bottle Tags",
        newTab: false,
        path: "/custom-bottle-tags",
      },
      {
        id: 84,
        title: "Postcards",
        newTab: false,
        path: "/postcards",
      },
      {
        id: 85,
        title: "Vouchers",
        newTab: false,
        path: "/vouchers",
      },
      {
        id: 86,
        title: "Tickets",
        newTab: false,
        path: "/tickets",
      },
      {
        id: 87,
        title: "Custom Printed Flags",
        newTab: false,
        path: "/custom-printed-flags",
      },
    ],
  },
  {
    id: 9,
    title: "Thesis Binding & A4 Printing",
    newTab: false,
    path: "/thesis-binding",
  },
  // {
  //   id: 9,
  //   title: "pages",
  //   newTab: false,
  //   path: "/",
  //   submenu: [
  //     {
  //       id: 91,
  //       title: "Shop With Sidebar",
  //       newTab: false,
  //       path: "/shop-with-sidebar",
  //     },
  //     {
  //       id: 92,
  //       title: "Shop Without Sidebar",
  //       newTab: false,
  //       path: "/shop-without-sidebar",
  //     },
  //     {
  //       id: 94,
  //       title: "Checkout",
  //       newTab: false,
  //       path: "/checkout",
  //     },
  //     {
  //       id: 95,
  //       title: "Cart",
  //       newTab: false,
  //       path: "/cart",
  //     },
  //     {
  //       id: 96,
  //       title: "Wishlist",
  //       newTab: false,
  //       path: "/wishlist",
  //     },
  //     {
  //       id: 97,
  //       title: "Sign in",
  //       newTab: false,
  //       path: "/signin",
  //     },
  //     {
  //       id: 98,
  //       title: "Sign up",
  //       newTab: false,
  //       path: "/signup",
  //     },
  //     {
  //       id: 99,
  //       title: "My Account",
  //       newTab: false,
  //       path: "/my-account",
  //     },
  //     {
  //       id: 93,
  //       title: "Error",
  //       newTab: false,
  //       path: "/error",
  //     },
  //     {
  //       id: 90,
  //       title: "Mail Success",
  //       newTab: false,
  //       path: "/mail-success",
  //     },
  //   ],
  // },

  // {
  //   id: 7,
  //   title: "blogs",
  //   newTab: false,
  //   path: "/",
  //   submenu: [
  //     {
  //       id: 71,
  //       title: "Blog Grid with sidebar",
  //       newTab: false,
  //       path: "/blogs/blog-grid-with-sidebar",
  //     },
  //     {
  //       id: 72,
  //       title: "Blog Grid",
  //       newTab: false,
  //       path: "/blogs/blog-grid",
  //     },
  //     {
  //       id: 73,
  //       title: "Blog details with sidebar",
  //       newTab: false,
  //       path: "/blogs/blog-details-with-sidebar",
  //     },
  //     {
  //       id: 74,
  //       title: "Blog details",
  //       newTab: false,
  //       path: "/blogs/blog-details",
  //     },
  //   ],
  // },
];
